return {
	Title = Color3.fromRGB(255, 255, 255),
	AreaOutline = Color3.fromRGB(61, 61, 61),

	Header = Color3.fromRGB(40, 40, 40),

	--#region Frame
	Background = Color3.fromRGB(40, 40, 40),
	Stroke = Color3.fromRGB(63, 63, 63),
	--#endregion Frame
	
	--#region Text
	Text = Color3.fromRGB(195, 195, 195),
	PlaceholderText = Color3.fromRGB(117, 117, 117),
	TextSelected = Color3.fromRGB(255, 255, 255),
	TextHighlight = Color3.fromRGB(238, 238, 238),
	TextMuted = Color3.fromRGB(124, 124, 124),
	InfoText = Color3.fromRGB(79, 152, 255),
	WarningText = Color3.fromRGB(255, 196, 0),
	ErrorText = Color3.fromRGB(255, 84, 84),
	SuccessText = Color3.fromRGB(88, 201, 105),
	CriticalText = Color3.fromRGB(180, 0, 0),
	NoticeText = Color3.fromRGB(101, 163, 255),
	--#endregion Text
	
	--#tag Button
	Button = Color3.fromRGB(40, 40, 40),
	ButtonSelected = Color3.fromRGB(71, 114, 179),
	ButtonText = Color3.fromRGB(195, 195, 195),
	ButtonTextOnSelected = Color3.fromRGB(255, 255, 255),
	ButtonHighlight = Color3.fromRGB(70, 70, 70),
	ButtonHighlightOnSelected = Color3.fromRGB(126, 161, 207),
	ButtonClickEffect = Color3.fromRGB(161, 161, 161),
		ButtonClickEffectImageContent = Content.fromAssetId(85482587748308),
	ButtonClickEffectTransparency = 0.5,
	ButtonIcon = Color3.fromRGB(220, 220, 220),
	ButtonIconOnSelected = Color3.fromRGB(255, 255, 255),

	--#tag Menu
	Menu = Color3.fromRGB(40, 40, 40),
	MenuSelected = Color3.fromRGB(71, 114, 179),
	MenuText = Color3.fromRGB(230, 230, 230),
	MenuTextOnSelected = Color3.fromRGB(255, 255, 255),
	MenuHighlight = Color3.fromRGB(70, 70, 70),
	MenuHighlightOnSelected = Color3.fromRGB(126, 161, 207),
	MenuClickEffect = Color3.fromRGB(161, 161, 161),
	MenuIcon = Color3.fromRGB(220, 220, 220),
	MenuIconOnSelected = Color3.fromRGB(255, 255, 255),

	--#tag MenuItem
	MenuItem = Color3.fromRGB(40, 40, 40),
	MenuItemSelected = Color3.fromRGB(71, 114, 179),
	MenuItemText = Color3.fromRGB(230, 230, 230),
	MenuItemTextOnSelected = Color3.fromRGB(255, 255, 255),
	MenuItemHighlight = Color3.fromRGB(70, 70, 70),
	MenuItemHighlightOnSelected = Color3.fromRGB(126, 161, 207),
	MenuItemClickEffect = Color3.fromRGB(161, 161, 161),
	MenuItemIcon = Color3.fromRGB(220, 220, 220),
	MenuItemIconOnSelected = Color3.fromRGB(255, 255, 255),

	--#tag PopupMenu
	PopupMenuItemLine = Color3.fromRGB(156, 156, 156),

	--#tag Slider
	SliderSelected = Color3.fromRGB(79, 83, 89),
	SliderHighlightOnSelected = Color3.fromRGB(111, 116, 125),

	--#tag RangeSlider
	SliderGaugeMin = Color3.fromRGB(101, 163, 255),
	SliderGaugeMax = Color3.fromRGB(101, 163, 255),
	SliderGaugeStroke = Color3.fromRGB(92, 144, 255),

	--#region Image
	InfoIcon = Color3.fromRGB(79, 152, 255),
	WarningIcon = Color3.fromRGB(255, 196, 0),
	ErrorIcon = Color3.fromRGB(255, 84, 84),
	SuccessIcon = Color3.fromRGB(88, 201, 105),
	CriticalIcon = Color3.fromRGB(180, 0, 0),
	NoticeIcon = Color3.fromRGB(101, 163, 255),

	--#region ScrollingFrame
	ScrollingFrame = Color3.fromRGB(40, 40, 40),
	ScrollBar = Color3.fromRGB(86, 86, 86),

	CullingFade = Color3.fromRGB(255, 255, 255),
	CullingFadeTransparency = 0.4,
}
